version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: cache
    ports:
      - "6379:6379"

  payment_service:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "8002:8000"
    environment:
      FAILURE_RATE: 0.1
      MAX_LATENCY: 0.5

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/orders_db
      PAYMENT_SERVICE_URL: http://payment_service:8000
    depends_on:
      - db
      - payment_service

  user_service:
    build: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      ORDER_SERVICE_URL: http://order_service:8000
    depends_on:
      - redis
      - order_service

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
